"""empty message

Revision ID: be7e3f21eaba
Revises: eebe409568c3
Create Date: 2020-08-27 12:20:17.750450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7e3f21eaba'
down_revision = 'eebe409568c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditory_log', 'message',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('auditory_log', 'method',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('auditory_log', 'module',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('auditory_log', 'proccess',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditory_log', 'proccess',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('auditory_log', 'module',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('auditory_log', 'method',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('auditory_log', 'message',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
