"""empty message

Revision ID: eebe409568c3
Revises: 86d00e9896b1
Create Date: 2020-08-27 12:16:08.011511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebe409568c3'
down_revision = '86d00e9896b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditory_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proccess', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditory_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditory_log')
    # ### end Alembic commands ###
